### ISSUE TITLE
"Load a TrackMate file" yields The source image is not loaded; cannot instantiates spot analyzers.

### ISSUE THREAD

**Issue by MaximeMaW** [fiji/TrackMate#104]
Hi,

First of all, thank you very much for this plugin. It is very easy to use and provided very good results to analyze my single particle datasets.

I am analyzing .nd2 files in Fiji (they are imported through the Bio-formats importer), and everything works fine with TrackMate. In the end, I clicked TrackMate's save button to store all the parameters used in the analysis for later use and reproducibility.

Now, TrackMate displays an error when I try to open the saved XML file.

1. I go to "Load a TrackMate file"
2. Then the Bio-formats window opens, suggesting that Fiji is able to find the .nd2 file linked with the .xml file.
3. When I click "Ok", the stack takes ~60s to load (which is normal)
4. At the same time, a "log window" appears with the message  `The source image is not loaded; cannot instantiates spot analyzers.`
5. Then, all the trajectories are properly loaded, but overlayed with a blank background instead of the movie.
6. In parallel, the movie opens, but does not seem to be connected with TrackMate

I was expecting to use this .xml file to easily go back in my analysis and get a sense of how individual trajectories look like.

Second (and I don't know whether the issue is related): when I load a .xml file, the TrackMate window initializes to the latest viewed panel. I tried to use the previous button but get the following error message when clicking "back"  on the "select detector" view: 

```
Exception in thread "TrackMate spot feature calculation thread." java.lang.IllegalArgumentException: Argument out of range: 1
	at ij.ImageStack.getProcessor(ImageStack.java:269)
	at net.imglib2.img.imageplus.ByteImagePlus.<init>(ByteImagePlus.java:101)
	at net.imglib2.img.ImagePlusAdapter.wrapByte(ImagePlusAdapter.java:243)
	at net.imglib2.img.ImagePlusAdapter.wrapLocal(ImagePlusAdapter.java:115)
	at net.imglib2.img.ImagePlusAdapter.wrap(ImagePlusAdapter.java:77)
	at net.imglib2.img.ImagePlusAdapter.wrapImgPlus(ImagePlusAdapter.java:94)
	at fiji.plugin.trackmate.util.TMUtils.rawWraps(TMUtils.java:110)
	at fiji.plugin.trackmate.features.SpotFeatureCalculator.computeSpotFeaturesAgent(SpotFeatureCalculator.java:157)
	at fiji.plugin.trackmate.features.SpotFeatureCalculator.process(SpotFeatureCalculator.java:93)
	at fiji.plugin.trackmate.TrackMate.computeSpotFeatures(TrackMate.java:174)
	at fiji.plugin.trackmate.gui.descriptors.ViewChoiceDescriptor$1.run(ViewChoiceDescriptor.java:94)
```

Thanks a lot for any suggestion to overcome these issues (actually the first one is the most critical).

**Comment by tinevez** [comment]
Hi @MaximeMaW 

TrackMate is limited to only reload ImageJ TIF files. If you use another file format, the image and the overlay will not be linked properly.

**Comment by MaximeMaW** [comment]
Hi @tinevez 

Thank you for your quick reply. I understand that supporting all the specificities of the Bio-formats module is a huge task and that there is no plan to dig into it.

However, I am not sure to understand the implications. Does it mean that there is no way to make this link between the image and the overlay manually (in a similar manner as the "refresh source" button)?

On an even more manual manner. If I export my movie to TIFF, how can I edit the saved file to now display the overlay on the TIFF instead of the ND2 file?

Thank you very much!

**Comment by imagejan** [comment]
@MaximeMaW this has been discussed on the forum. See for example:
http://forum.imagej.net/t/trackmate-error-when-loading-a-saved-xml-linked-to-zvi/4683?u=imagejan

**Comment by MaximeMaW** [comment]
@imagejan Thanks a lot!
