### ISSUE TITLE
bug while loading trackmate xml file

### ISSUE THREAD

**Issue by haesleinhuepf** [fiji/TrackMate#105]
Hey @tinevez, hey guys,

I just had a nullpointer exception popping up when trying to reload a trackmate xml file, which was saved a minute before:

(Fiji Is Just) ImageJ 2.0.0-rc-61/1.51n; Java 1.8.0_66 [64-bit]; Mac OS X 10.12.5; 57MB of 9834MB (<1%)
 
java.lang.NullPointerException
	at fiji.plugin.trackmate.io.TmXmlReader.getVersion(TmXmlReader.java:458)
	at fiji.plugin.trackmate.LoadTrackMatePlugIn_.run(LoadTrackMatePlugIn_.java:148)
	at ij.IJ.runUserPlugIn(IJ.java:217)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)

And this is the file:
https://gist.github.com/haesleinhuepf/2e505d9ae8de2ef884a7982d5106ddff

So, the error happens here: 
https://github.com/fiji/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/io/TmXmlReader.java#L458

And may have something to do with this line:
https://github.com/fiji/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/io/TmXmlKeys.java#L23

Because, there is no "version" attribute in the root element. It just says:
from="TrackMate v3.5.1-SNAPSHOT"

But renaming the attribute to "version" does also not work:
(Fiji Is Just) ImageJ 2.0.0-rc-61/1.51n; Java 1.8.0_66 [64-bit]; Mac OS X 10.12.5; 70MB of 9834MB (<1%)
 
java.lang.IllegalArgumentException: Invalid version format: TrackMate v3.5.1
	at fiji.plugin.trackmate.util.Version.<init>(Version.java:25)
	at fiji.plugin.trackmate.LoadTrackMatePlugIn_.run(LoadTrackMatePlugIn_.java:148)
	at ij.IJ.runUserPlugIn(IJ.java:217)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)

I'm not sure, how to fix the bug. That's why I'm posting it here. But I'm happy to help. :-)

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
Ah right. I see. My fault! Thanks anyway :)
