### ISSUE TITLE
DoG Detector Error

### ISSUE THREAD

**Issue by squinnlee** [fiji/TrackMate#131]
Hello,

I am trying to re-analyze some images using the DoG detector in TrackMate and I am getting an error. It has worked before a few weeks ago, but when I tried analyzing my images today it would not work. I get an error when I select the next button or the preview button after selecting the DoG detector. I tried some of the ImageJ sample images, and it still will not work. It is the DoG detector specifically, because I tried the LoG detector and saw no issues. I am just trying to figure out if something is happening on my end and/or what I can do to fix it.

Here's what it says when I press preview after selecting my blog diameter and threshold: 
Exception in thread "TrackMate preview detection thread" java.lang.ArrayIndexOutOfBoundsException: 2
	at net.imglib2.algorithm.convolution.LineConvolution.requiredSourceInterval(LineConvolution.java:46)
	at net.imglib2.algorithm.convolution.Concatenation.tmpIntervals(Concatenation.java:110)
	at net.imglib2.algorithm.convolution.Concatenation.process(Concatenation.java:60)
	at net.imglib2.algorithm.gauss3.Gauss3.gauss(Gauss3.java:207)
	at net.imglib2.algorithm.gauss3.Gauss3.gauss(Gauss3.java:168)
	at fiji.plugin.trackmate.detection.DogDetector.process(DogDetector.java:84)
	at fiji.plugin.trackmate.TrackMate$1.run(TrackMate.java:377)
	at net.imglib2.multithreading.SimpleMultiThreading.startAndJoin(SimpleMultiThreading.java:126)
	at fiji.plugin.trackmate.TrackMate.execDetection(TrackMate.java:458)
	at fiji.plugin.trackmate.gui.panels.detector.LogDetectorConfigurationPanel$1.run(LogDetectorConfigurationPanel.java:233)

What it says when I press next:
Starting detection using DoG detector
with settings:
  - target channel: 1
  - threshold: 2.0
  - do median filtering: false
  - radius: 0.125
  - do subpixel localization: true
Starting detection process using 4 threads.
Detection processes 1 frame simultaneously and allocates 4 threads per frame.
An error occured:
java.lang.ArrayIndexOutOfBoundsException: 2
java.lang.ArrayIndexOutOfBoundsException: 2
	at net.imglib2.algorithm.convolution.LineConvolution.requiredSourceInterval(LineConvolution.java:46)
	at net.imglib2.algorithm.convolution.Concatenation.tmpIntervals(Concatenation.java:110)
	at net.imglib2.algorithm.convolution.Concatenation.process(Concatenation.java:60)
	at net.imglib2.algorithm.gauss3.Gauss3.gauss(Gauss3.java:207)
	at net.imglib2.algorithm.gauss3.Gauss3.gauss(Gauss3.java:168)
	at fiji.plugin.trackmate.detection.DogDetector.process(DogDetector.java:84)
	at fiji.plugin.trackmate.TrackMate$1.run(TrackMate.java:377)
	at net.imglib2.multithreading.SimpleMultiThreading.startAndJoin(SimpleMultiThreading.java:126)
	at fiji.plugin.trackmate.TrackMate.execDetection(TrackMate.java:458)
	at fiji.plugin.trackmate.gui.descriptors.DetectionDescriptor$1.run(DetectionDescriptor.java:88)
Detection done in 0.0 s.

**Comment by squinnlee** [comment]
By the way, I also tried re-installing Fiji

**Comment by tinevez** [comment]
Can you give me the dimension of the image you ran TrackMate on please?

**Comment by squinnlee** [comment]
My image is 20.48x20.48 microns (512x512); 32-bit, 121 MB. I tried converting the file to 8-bit and still got an error. I have also tried one of ImageJ's sample images that was 513x282 pixels; 8-bit, 141 kb to no avail.
If you need the calibration settings, screenshots, or anything else, please let me know.
Thank you!

**Comment by squinnlee** [comment]
I forgot to include: My image has 121 time points

**Comment by imagejan** [comment]
Might be related to https://github.com/imglib/imglib2-algorithm/issues/77 and recent changes in the `net.imglib2.algorithm.gauss3.Gauss3` implementation.

Would be worth checking if it still occurs with `imglib2-algorithm-0.11.1`.

**Comment by squinnlee** [comment]
Hopefully this is a small bug. Thank you so much for your help!

**Comment by tinevez** [comment]
Sorry I still lack the time to do it....

**Comment by ctrueden** [comment]
@tinevez Do you need assistance? Are you able to post an MCVE here?

**Comment by tinevez** [comment]
Found it!
It was a dimensionality issue with the sigma array used in the `Gauss3` calls.
