### ISSUE TITLE
Semi-automatic tracking fails with multi-channel image sequences

### ISSUE THREAD

**Issue by snownontrace** [fiji/TrackMate#152]
The semi-automatic tracking tool is a great help for manual tracking. It works like a charm when a single-channel image sequence was used. However, when working with multi-channel images, however, it gives the following error message:

```java
Exception in thread "TrackMate semi-automated tracking thread" java.lang.ArrayIndexOutOfBoundsException: 2
	at net.imglib2.transform.integer.MixedTransform.setTranslation(MixedTransform.java:150)
	at net.imglib2.view.Views.offset(Views.java:490)
	at fiji.plugin.trackmate.detection.DetectionUtils.copyToFloatImg(DetectionUtils.java:134)
	at fiji.plugin.trackmate.detection.LogDetector.process(LogDetector.java:107)
	at fiji.plugin.trackmate.detection.semiauto.AbstractSemiAutoTracker.processSpot(AbstractSemiAutoTracker.java:214)
	at fiji.plugin.trackmate.detection.semiauto.AbstractSemiAutoTracker$1.run(AbstractSemiAutoTracker.java:150)
	at java.lang.Thread.run(Thread.java:748)
	at net.imglib2.multithreading.SimpleMultiThreading.startAndJoin(SimpleMultiThreading.java:126)
	at fiji.plugin.trackmate.detection.semiauto.AbstractSemiAutoTracker.process(AbstractSemiAutoTracker.java:155)
	at fiji.plugin.trackmate.visualization.hyperstack.SpotEditTool$3.run(SpotEditTool.java:1171)
```

It will be great if it can settle with the current channel. Thanks!

**Comment by tinevez** [comment]
Hello @snownontrace 

Sorry I only looked at the problem now. Since your report I have been working on the future version of TrackMate (v7) that should be out this summer. At least in this version, the bug is not there. 
Please let met know if you see it happening again after the new version release.
Thanks
