### ISSUE TITLE
Upload batick-codec

### ISSUE THREAD

**Issue by tinevez** [fiji/TrackMate#182]
The SVG export of charts require batik-codec to be in the classpath, lest an exception is thrown:

```java
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.apache.batik.svggen.ImageHandlerBase64Encoder.encodeImage(ImageHandlerBase64Encoder.java:157)
	at org.apache.batik.svggen.ImageHandlerBase64Encoder.handleHREF(ImageHandlerBase64Encoder.java:133)
	at org.apache.batik.svggen.ImageHandlerBase64Encoder.handleHREF(ImageHandlerBase64Encoder.java:72)
	at org.apache.batik.svggen.DefaultImageHandler.handleImage(DefaultImageHandler.java:63)
	at org.apache.batik.svggen.SimpleImageHandler.handleImage(SimpleImageHandler.java:100)
	at org.apache.batik.svggen.SVGGraphics2D.drawImage(SVGGraphics2D.java:676)
```

This problem is caused when the artifact `batick-codec` is not on the classpath.
See https://stackoverflow.com/questions/16138850/batik-svggraphics2d-nullpointerexception-when-drawing-image

**Comment by tinevez** [comment]
Solved with TrackMate v7, released today.
