### ISSUE TITLE
TrackMate GUI not starting when the GDSC update site is activated

### ISSUE THREAD

**Issue by giocard** [fiji/TrackMate#192]
This is the error message

```
(Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 218MB of 24459MB (<1%)
 
java.lang.NoClassDefFoundError: fiji/plugin/trackmate/gui/ConfigurationPanel
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:304)
	at fiji.plugin.trackmate.providers.AbstractProvider.registerModules(AbstractProvider.java:77)
	at fiji.plugin.trackmate.providers.AbstractProvider.<init>(AbstractProvider.java:45)
	at fiji.plugin.trackmate.providers.DetectorProvider.<init>(DetectorProvider.java:32)
	at fiji.plugin.trackmate.gui.wizard.TrackMateWizardSequence.<init>(TrackMateWizardSequence.java:135)
	at fiji.plugin.trackmate.TrackMatePlugIn.createSequence(TrackMatePlugIn.java:115)
	at fiji.plugin.trackmate.TrackMatePlugIn.run(TrackMatePlugIn.java:96)
	at fiji.plugin.trackmate.TrackMateRunner.run(TrackMateRunner.java:539)
	at ij.IJ.runUserPlugIn(IJ.java:241)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: fiji.plugin.trackmate.gui.ConfigurationPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
```

**Comment by aherbert** [comment]
The GDSC plugin is based on TrackMate 6. TrackMate recently reworked the entire codebase for [version 7](https://github.com/fiji/TrackMate/releases/tag/TrackMate-7.0.4). The two plugins are incompatible.

The solution would be to remove TrackMate features from the GDSC plugin and move them to a separate GDSC TrackMate plugin which can be enabled separately.

What part of the GDSC plugin are you using? If it is not the TrackMate features then dropping those would fix this issue for all users of TrackMate who have the GDSC plugins. This can be fixed quickly. Creation of a new GDSC TrackMate plugin will take longer.

**Comment by tinevez** [comment]
I can also help migrating GDSC to TrackMate v7. I did it for other plugins.
Who is behind GSDC and what does it do?

**Comment by giocard** [comment]
@aherbert is the maintainer. The plugin provides several dedicated tools for colocalization, spot detection and cell segmentation. At least these are the functionalities I am aware of.

**Comment by tinevez** [comment]
@aherbert I can offer to work on your project if you let me. I would try to upgrade the TrackMate part and bring it along the new v7.

**Comment by aherbert** [comment]
@tinevez Thanks for the offer. I saw your release note on version 7 and it has features I would like to use. Currently I have two addins for TrackMate. One loads precomputed spots. We were using it to load cell locations identified by ilastik. This may be obsolete now if TrackMate directly supports ilastik. The other is a detector that outlines cell nuclei. With the new support for contour outlines this addin will be much better supported in TM7. I also have some code for actions and features.

I will do a quick release of the GDSC plugin with all the TrackMate code removed. This will remove any conflict. I will then spend some time looking at the new API for how I can update my nuclei detector and the other custom extensions.

**Comment by aherbert** [comment]
@giocard I have just released the GDSC plugin with no TrackMate features. Please update Fiji and verify this fixes the TrackMate start-up issue.
