### ISSUE TITLE
TrackMate crashes when saving.

### ISSUE THREAD

**Issue by tinevez** [fiji/TrackMate#206]
A spot feature (what one is to be determined) has missing information (`isInt()`) that crashes the XML writer when saving. Here is the NPE:

```java
writer.appendModel(model)

at fiji.plugin.trackmate.io.TmXmlWriter.marshalSpot(TmXmlWriter.java:717)
at fiji.plugin.trackmate.io.TmXmlWriter.echoSpots(TmXmlWriter.java:540)
at fiji.plugin.trackmate.io.TmXmlWriter.appendModel(TmXmlWriter.java:229)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
java.lang.NullPointerException: java.lang.NullPointerException
```

The faulty line:
https://github.com/fiji/TrackMate/blob/4abaaf180f34728845df69abe83ff5efb3682ae7/src/main/java/fiji/plugin/trackmate/io/TmXmlWriter.java#L717

Discussed here: https://forum.image.sc/t/updating-trackmate-multichannel-measurement-script-to-new-trackmate-version/61466

**Comment by tinevez** [comment]
Added a safeguard here: 520aff9cf47ef6dfd047833bb6f5d7701fd8ce42
