### ISSUE TITLE
Trackmate does not open from eclipse

### ISSUE THREAD

**Issue by kapoorlab** [fiji/TrackMate#211]
Hello, I cloned the latest version of Trackmate and tried to launch Trackmate from Eclipse 

(
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2021-12 (4.22.0)
Build id: 20211202-1639) 
), Java SE 1.8 
and I am unable to do so and get this error:

`Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field private java.util.Hashtable java.awt.Font.fRequestedAttributes accessible: module java.desktop does not "opens java.awt" to unnamed module @63a270c9
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

...

at fiji.plugin.trackmate.gui.displaysettings.DisplaySettingsIO.toJson(DisplaySettingsIO.java:59)
	at fiji.plugin.trackmate.gui.displaysettings.DisplaySettingsIO.saveToUserDefault(DisplaySettingsIO.java:88)
	at fiji.plugin.trackmate.gui.displaysettings.DisplaySettingsIO.readUserDefault(DisplaySettingsIO.java:109)
	at fiji.plugin.trackmate.TrackMatePlugIn.createDisplaySettings(TrackMatePlugIn.java:183)
	at fiji.plugin.trackmate.TrackMatePlugIn.run(TrackMatePlugIn.java:91)
	at fiji.plugin.trackmate.TrackMatePlugIn.main(TrackMatePlugIn.java:191)`

Problem with eclipse version?

**Comment by tinevez** [comment]
This is the Eclipse version with which I develop TrackMate.
Can I see the full log? Apparently it crashes because it does not manage to serialize the display settings via GSon. 
Did you clone the repo without any modification?

**Comment by kapoorlab** [comment]
Yeah I just cloned the repo and tried to run it with an image, it opens the image asks me to swap Z and T and then this shows up:

`Could not read the last used settings file at C:\Users\rando\.trackmate\lastusedsettings.xml.
Using built-in defaults.
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field private java.util.Hashtable java.awt.Font.fRequestedAttributes accessible: module java.desktop does not "opens java.awt" to unnamed module @79c7532f
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.toJson(Gson.java:696)
	at com.google.gson.Gson.toJson(Gson.java:683)
	at com.google.gson.Gson.toJson(Gson.java:638)
	at com.google.gson.Gson.toJson(Gson.java:618)
	at fiji.plugin.trackmate.gui.displaysettings.DisplaySettingsIO.toJson(DisplaySettingsIO.java:59)
	at fiji.plugin.trackmate.gui.displaysettings.DisplaySettingsIO.saveToUserDefault(DisplaySettingsIO.java:88)
	at fiji.plugin.trackmate.gui.displaysettings.DisplaySettingsIO.readUserDefault(DisplaySettingsIO.java:109)
	at fiji.plugin.trackmate.TrackMatePlugIn.createDisplaySettings(TrackMatePlugIn.java:183)
	at fiji.plugin.trackmate.TrackMatePlugIn.run(TrackMatePlugIn.java:91)
	at fiji.plugin.trackmate.TrackMatePlugIn.main(TrackMatePlugIn.java:191)`

**Comment by tinevez** [comment]
Sorry I cannot reproduce.

From the trace it seems that GSon has a hard time serializing something related to AWT, probably the font in the display settings (line 110 in the `DisplaySettings` class).

Here are a few hints:

- Check that you are using Java JDK 8 in Eclipse.
- What happens if you run maven in the repo?
- If it compiles, what happens if you drop the SNAPSHOT jar into Fiji?
- Finally if nothing works, we will have to edit the DisplaySettings class to investigate more.
-

**Comment by kapoorlab** [comment]
Yes, the problem was using jre instead of jdk in Eclipse. In Fiji the snapshot jar worked fine as well. Thanks.
