### ISSUE TITLE
Make Median filter work on n-dimensional images

### ISSUE THREAD

**Issue by imagejan** [fiji/TrackMate#67]
Currently, the median filter offered during spot detection works on 2D images only, because a 3x3 neighborhood is [hardcoded here](https://github.com/fiji/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/detection/util/MedianFilter.java#L48):

    final float[] values = new float[ 9 ];

This should either:
- differentiate between 2D and 3D explicitly (`new float[ 27 ]`) or
- avoid hard-coding the filter completely and use imagej-ops instead: `ops().filter().median(...)`

The exception thrown when using median filter with 3D images is:

```
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:915)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1217)
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:218)
	at java.util.concurrent.FutureTask.get(FutureTask.java:83)
	at net.imglib2.algorithm.fft2.FFTMethods.complexToComplex(FFTMethods.java:901)
	at net.imglib2.algorithm.fft2.FFT.realToComplex(FFT.java:248)
	at net.imglib2.algorithm.fft2.FFT.realToComplex(FFT.java:123)
	at net.imglib2.algorithm.fft2.FFT.realToComplex(FFT.java:74)
	at net.imglib2.algorithm.fft2.FFTConvolution.convolve(FFTConvolution.java:525)
	at fiji.plugin.trackmate.detection.LogDetector.process(LogDetector.java:136)
	at fiji.plugin.trackmate.TrackMate$1.run(TrackMate.java:433)
Exception in thread "TrackMate preview detection thread" java.lang.ArrayIndexOutOfBoundsException: 9
	at fiji.plugin.trackmate.detection.util.MedianFilter.process(MedianFilter.java:69)
	at fiji.plugin.trackmate.detection.DetectionUtils.applyMedianFilter(DetectionUtils.java:177)
	at fiji.plugin.trackmate.detection.LogDetector.process(LogDetector.java:113)
	at fiji.plugin.trackmate.TrackMate$1.run(TrackMate.java:433)
	at net.imglib2.multithreading.SimpleMultiThreading.startAndJoin(SimpleMultiThreading.java:126)
	at fiji.plugin.trackmate.TrackMate.execDetection(TrackMate.java:505)
	at fiji.plugin.trackmate.gui.panels.detector.LogDetectorConfigurationPanel$1.run(LogDetectorConfigurationPanel.java:230)
```

**Comment by tinevez** [comment]
Hi @imagejan,
Actually this corresponded to cases where I wanted to apply a median filter specifically in the image plane for classical microscopes. I wanted it to operate on 2D planes even for 3D images. 
I don't think it is worth the effort to implement a 3D filter as an optional parameter for TrackMate detectors. 

However, if you mean that ImgLib2 should ship a nD median filter, then I follow you :)

**Comment by imagejan** [comment]
@tinevez alright, I see the point.
Then I'd suggest that either `Neighborhood` or `Cursor` get restricted to the xy plane instead, to avoid said exception to be thrown when `nc` has more than 9 elements (see https://github.com/fiji/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/detection/util/MedianFilter.java#L69).

**Comment by tinevez** [comment]
Wait, I am slow but I see your point. You mean that there is a BUG and that the software crashes when you try to use median on a 3D image? 
If yes it's a bug and there is no arguing - I shall fix it.
