### ISSUE TITLE
Export to Icy tracks fail.

### ISSUE THREAD

**Issue by tinevez** [fiji/TrackMate#84]
Launching the action with v3.3.0 allows the user to select the target file, but then an exception is raised:

`Exception in thread "TrackMate action thread" java.lang.NullPointerException
    at fiji.plugin.trackmate.io.IcyTrackFormatWriter.process(IcyTrackFormatWriter.java:165)
    at fiji.plugin.trackmate.action.IcyTrackExporter.execute(IcyTrackExporter.java:80)
    at fiji.plugin.trackmate.gui.panels.ActionChooserPanel$1$1.run(ActionChooserPanel.java:127)`

**Comment by tinevez** [comment]
False alarm. It works as expected.
