### ISSUE TITLE
Bug calculating spots intensities

### ISSUE THREAD

**Issue by hadim** [fiji/TrackMate#91]
Using a fresh and updated Fiji version I have the following error during a LOG/DOG detection : 

```
Exception in thread "TrackMate spot feature calculating thread 1/8" java.lang.ArrayIndexOutOfBoundsException: 7
	at fiji.plugin.trackmate.features.spot.SpotIntensityAnalyzer.process(SpotIntensityAnalyzer.java:86)
	at fiji.plugin.trackmate.features.SpotFeatureCalculator$1.run(SpotFeatureCalculator.java:185)
```
In consequence spots can't be filtered by their intensitiy values.

The bug only happens with my dataset (it works well with Sample for Trackmate).

The problematic file can be found here : https://file.io/5NQfcf

**Comment by tinevez** [comment]
Hi @hadim 
The data is not accessible anymore. Can you send it again please?

**Comment by hadim** [comment]
Unfortunately I don't remember which dataset was it.... I'll try to reproduce it and keep you in touch.
