### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by tischi** [fiji/TrackMate#92]
Hello,

we were running like this:

Starting detection using Downsample LoG detector
with settings:
  - target channel: 1
  - downsample factor: 4
  - threshold: 1000.0
  - radius: 1.25
Starting detection process using 8 threads.

and got this error:

```
java.lang.ArithmeticException: / by zero
	at net.imglib2.util.IntervalIndexer.indexToPosition(IntervalIndexer.java:110)
	at net.imglib2.img.array.AbstractArrayLocalizingCursor.reset(AbstractArrayLocalizingCursor.java:218)
	at net.imglib2.img.array.AbstractArrayLocalizingCursor.<init>(AbstractArrayLocalizingCursor.java:138)
	at net.imglib2.img.array.ArrayLocalizingCursor.<init>(ArrayLocalizingCursor.java:68)
	at net.imglib2.img.array.ArrayImg.localizingCursor(ArrayImg.java:104)
	at net.imglib2.img.array.ArrayImg.localizingCursor(ArrayImg.java:61)
	at fiji.plugin.trackmate.detection.DownsampleLogDetector.process(DownsampleLogDetector.java:143)
	at fiji.plugin.trackmate.TrackMate$1.run(TrackMate.java:377)
```

**Comment by tinevez** [comment]
Hi @tischi 
I cannot reproduce the error. Can you send me the image data and parameters?

**Comment by tischi** [comment]
Hi, I told the user (see the private e-mail that I sent you).

**Comment by tinevez** [comment]
Hi @tischi 
I looked in my emails and it looks like I either lost the email, or the user never contacted me with the data. Can you have it send to me again please?
