### ISSUE TITLE
error when working with big file

### ISSUE THREAD

**Issue by tischi** [fiji/TrackMate#96]
Hi,
We tried TrackMate with a file where one timepoint is 3.7GB, nx,ny,nz 2057,1160,851.
And we got below error message. Is this due to a java indexing issue?!

Exception in thread "TrackMate preview detection thread" java.lang.RuntimeException: Number of elements in Container too big, use for example CellContainer instead: 2796393600 > 2147483647
	at net.imglib2.img.array.ArrayImgFactory.numEntitiesRangeCheck(ArrayImgFactory.java:71)
	at net.imglib2.img.array.ArrayImgFactory.createFloatInstance(ArrayImgFactory.java:103)
	at net.imglib2.img.array.ArrayImgFactory.createFloatInstance(ArrayImgFactory.java:58)
	at net.imglib2.type.numeric.complex.ComplexFloatType.createSuitableNativeImg(ComplexFloatType.java:93)
	at net.imglib2.img.array.ArrayImgFactory.create(ArrayImgFactory.java:63)
	at net.imglib2.img.array.ArrayImgFactory.create(ArrayImgFactory.java:58)
	at net.imglib2.algorithm.fft2.FFT.realToComplex(FFT.java:116)
	at net.imglib2.algorithm.fft2.FFT.realToComplex(FFT.java:74)
	at net.imglib2.algorithm.fft2.FFTConvolution.convolve(FFTConvolution.java:521)
	at fiji.plugin.trackmate.detection.LogDetector.process(LogDetector.java:136)
	at fiji.plugin.trackmate.TrackMate$1.run(TrackMate.java:377)
	at net.imglib2.multithreading.SimpleMultiThreading.startAndJoin(SimpleMultiThreading.java:126)
	at fiji.plugin.trackmate.TrackMate.execDetection(TrackMate.java:449)
	at fiji.plugin.trackmate.gui.panels.detector.LogDetectorConfigurationPanel$1.run(LogDetectorConfigurationPanel.java:233)

**Comment by tinevez** [comment]
Yep.
We try to use an image data structure that can only have 2147483647 pixels, but your time point has 2796393600. 

What surprises me is that the imglib2 code in `createSuitableNativeImg` should provide automatically an alternative image factory depending on the image size, and apparently it did not pick the right one. 

Let me investigate this.

**Comment by tinevez** [comment]
Hi @tischi 
Can you test this fix by pulling and compiling from the master please?

**Comment by tischi** [comment]
I will do it as soon as possible. Currently I am drowning a bit in work, so it could take a bit.
